export const Location = [
 { id: 0, option: "English" },
 { id: 1, option: "Telgu" },
 { id: 2, option: "Tamil" },
 { id: 3, option: "Italian" },
 { id: 4, option: "Urdu" },
 { id: 5, option: "Hindi" },
]

export const TimeZone = [
    { id: 0, option: "Columbia UTC−08:00 (PT)" },
    { id: 1, option: "Nunavut UTC−05:00 (ET)" },
    { id: 2, option: "Pacific/Honolulu UTC−10:00 (HST)" },
    { id: 3, option: "America/Anchorage UTC−09:00 (AKST)" },
    { id: 4, option: "America/Los_Angeles UTC−08:00 (PST)" },
    { id: 5, option: "America/Denver UTC−07:00 (MST)" },
    { id: 6, option: "America/Chicago UTC−06:00 (CST)" },
    { id: 7, option: "America/New_York UTC−05:00 (EST)" },
    { id: 8, option: "Atlantic/Bermuda UTC−04:00 (AST)" },
    { id: 9, option: "America/Halifax UTC−04:00 (AST)" },
    { id: 10, option: "America/St_Johns UTC−03:30 (NST)" },
    { id: 11, option: "America/Argentina/Buenos_Aires UTC−03:00 (ART)" },
    { id: 12, option: "Atlantic/South_Georgia UTC−02:00 (GST)" },
    { id: 13, option: "Atlantic/Azores UTC−01:00 (AZOT)" },
    { id: 14, option: "UTC UTC+00:00 (UTC)" },
    { id: 15, option: "Europe/London UTC+00:00 (GMT)" },
    { id: 16, option: "Europe/Berlin UTC+01:00 (CET)" },
    { id: 17, option: "Europe/Athens UTC+02:00 (EET)" },
    { id: 18, option: "Asia/Baghdad UTC+03:00 (AST)" },
    { id: 19, option: "Asia/Tehran UTC+03:30 (IRST)" },
    { id: 20, option: "Asia/Dubai UTC+04:00 (GST)" },
    { id: 21, option: "Asia/Kabul UTC+04:30 (AFT)" },
    { id: 22, option: "Asia/Karachi UTC+05:00 (PKT)" },
    { id: 23, option: "Asia/Kolkata UTC+05:30 (IST)" },
    { id: 24, option: "Asia/Kathmandu UTC+05:45 (NPT)" },
    { id: 25, option: "Asia/Dhaka UTC+06:00 (BST)" },
    { id: 26, option: "Asia/Yangon UTC+06:30 (MMT)" },
    { id: 27, option: "Asia/Bangkok UTC+07:00 (ICT)" },
    { id: 28, option: "Asia/Hong_Kong UTC+08:00 (HKT)" },
    { id: 29, option: "Asia/Tokyo UTC+09:00 (JST)" },
    { id: 30, option: "Australia/Adelaide UTC+09:30 (ACDT)" },
    { id: 31, option: "Australia/Sydney UTC+10:00 (AEDT)" },
    { id: 32, option: "Pacific/Noumea UTC+11:00 (NCT)" },
    { id: 33, option: "Pacific/Auckland UTC+12:00 (NZDT)" },
    { id: 34, option: "Pacific/Chatham UTC+12:45 (CHAST)" }
]

export const OptionalParameters = [
    { id: 0, option: "option1" },
    { id: 1, option: "option2" },
    { id: 2, option: "option3" },
    { id: 3, option: "option4" },
    { id: 4, option: "option5" },
    { id: 5, option: "option6" },
   ]
   